name: Hello World
on:
  workflow_dispatch:
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: python /home/runner/work/python_answers/python_answers/hello.py
